### ISSUE TITLE
Feature Request for more generalized clipping.

### ISSUE THREAD

**Issue by stolk** [JCash/voronoi#12]
It would be great if the clipping, which is currently against a rectangle, could be performed on a more generic shape, for instance, a convex polygon.

This way, jc_voronoi would be able to decompose any given convex polygon.

**Comment by david94133** [comment]
This would be useful for me, because I would like to have "voronoi inside voronoi", where there are two levels -- divide a voronoi cell into perhaps 20 sections, using voronoi.

**Comment by indigoabstract** [comment]
Hi, thank you for sharing this very useful and high quality library!

I'm looking to clip against a voronoi cell/convex-poly as well (to make a recursive "voronoi inside voronoi"). If you do manage to get around to it, I'm sure it would be a great addition.
