### ISSUE TITLE
Site-point collisions

### ISSUE THREAD

**Issue by kewp** [JCash/voronoi#20]
Not sure where to put these comments / requests for info ...

(Thanks for creating this library, btw ! Has saved me a lot of time and brain power)

Is there an easy way to determine which site within the rectangle belongs to an x,y co-ordinate ? All I can think to do is loop through each one and do a polygonal collision check using each edge but I figured Voronoi is sort-of designed to know which points belong inside (that's basically the definition of a Voronoi diagram).

**Comment by kewp** [comment]
I suppose one way is just to loop through each point (site point) and check the distance and then the minimum one is the site the point belongs in

**Comment by mathiaswking** [comment]
"Not sure where to put these comments / requests for info"
Me neither, but this is fine I think :)

So, for a random point(x,y) you want to find what cell/site it belongs to?
I'm guessing the simplest way would be to go through each cell, and check if the point is outside or not:
for each site:
  for each edge:
    normal = site.pos - edge.pos[0] // pointing "inwards"
    v = testpos - edge.pos[0]
    if dot(normal, v) < 0: // The normals are opposite each other
      break // it's outside of this cell

**Comment by kewp** [comment]
I'm not sure I understand why a negative dot product means it is outside ?
I assume if you get to the end of the inner loop, you must be inside ?

**Comment by mathiaswking** [comment]
Oops, a bit sloppy there by me. The normal of course has to be orthogonal to the edge.
diff = edge.pos[1] - edge.pos[0]
normal = point(-diff.y, diff.x) // pointing inwards

It's a check to see if a point is in front or behind a plane. In this case the plane is in 2D (an edge), and the front face of the plane is facing the site. If the dot product between two vectors is negative, it means they point in opposite directions in relation to the plane.

**Comment by kewp** [comment]
I'm getting strange anomolies near the edges - maybe the point algorithm doesn't work there ?

[image](https://imgur.com/a/cErMzTf)

**Comment by kewp** [comment]
Think the algorithm is right. I used the distance algorithm I described earlier and I'm getting the same result.

I think the problem is that I'm plotting with dots so it inevitably looks aliased

**Comment by kewp** [comment]
Yup. Looks better when I use smaller points [image](https://imgur.com/a/GIAtVrV)
