### ISSUE TITLE
Indexes outside of allocated buffer.

### ISSUE THREAD

**Issue by lundmark** [JCash/voronoi#3]
Using 1000 points randomized in 0..2048 x 0..2048 space, the code goes into jcv_pq_push() with a pq->numitems extending over the pq->maxnumitems variable. 

If I use 16 000 points, it happens as well. The reason to this is because the max_num_events in the jcv_diagram_generate_useralloc() seems to be very low, and is never checked against in runtime.

**Comment by JCash** [comment]
I've now fixed this issue by simply allowing N events for N points. I'm not sure if there is a scenario where you would need _more_ than that, but it should suffice for now. It's a simple and cheap (low memory) solution.

https://github.com/JCash/voronoi/pull/5
