### ISSUE TITLE
half edge neighbor is incorrect

### ISSUE THREAD

**Issue by godpenguin7** [JCash/voronoi#37]
when i iterate through a site's halfedges and look at their neighbors, they do not correspond to actual neighbors. and even if i look at the half edge's corresponding edge, its two sites are not neighboring in the diagram.
![untitled](https://user-images.githubusercontent.com/31786313/50391423-b476c880-0712-11e9-99a2-e25a99c53f29.png)

**Comment by JCash** [comment]
Hi!

The array is sorted with respect to the points, so i != site->index

Try “myCells[ site->index ].selected = true;”
and see if that makes a difference
