### ISSUE TITLE
Crashes on division by zero

### ISSUE THREAD

**Issue by lundmark** [JCash/voronoi#4]
Crashes on division by zero in the jcv_edge_create where dx AND dy is both 0. The reason to this is because s1 == s2 is true.

**Comment by JCash** [comment]
I haven't been able to reproduce this. Do you happen to remember how you produced the point set?

**Comment by lundmark** [comment]
Hmm I just generated a couple of thousand points randomized between 0.0 and 2048.0 in both x and y axis. It is possible that points existed so that they were incredibly close to each other if that might be the issue?

**Comment by JCash** [comment]
I still haven't seen this in action, will close for now, and we can reopen when we know more and have more test data.
