### ISSUE TITLE
Unneccessary assignment?

### ISSUE THREAD

**Issue by lundmark** [JCash/voronoi#45]
https://github.com/JCash/voronoi/blob/f5e9cf221f5570f75d5d7e00cac3866e1b1c47e4/src/jc_voronoi.h#L1390

Not sure if there is an underlying issue here, but doing this twice seems unnecessary?

**Comment by mathiaswking** [comment]
Good call. They're remnants of previous code that I tried out. This needs to be looked at and cleared up.

**Comment by JCash** [comment]
Fixed in https://github.com/JCash/voronoi/pull/46
