### ISSUE TITLE
#define JCV_SQRT sqrt when using double

### ISSUE THREAD

**Issue by yoavmil** [JCash/voronoi#51]
First of, I used you library and it works great out of the box! 

When using double, and not doing `#define JCV_SQRT sqrt`, gives warnings. you just missed it in the readme.md.

also a couple of feature requests, I could do some if you want:
- let the user define JCV_REAL_TYPE double/float, and hide all other macros under the hood.
- have a c++ wrapper, replacing the array pointer with std::vector etc.
- support segments in addition to points - this is a big request.

**Comment by JCash** [comment]
Thanks for using it!

I'll add JCV_SQRT to the docs!

1) Sounds like a good suggestion

2) Not sure why a C++ wrapper is needed, I think it will only obfuscate the data.
Not to mention slow things down, and add code size and complexity.

3) Yes, I've thought about that, but I'm afraid it's such a big task, that I'm most likely never going to have time to add that.
