### ISSUE TITLE
Usage of Voronoi library

### ISSUE THREAD

**Issue by Lena1111111111** [JCash/voronoi#55]
Hello, my name is Lena and I am trying to work with algorithm Event-chain and I need Voroni diagram to do it to find nearest neighbors (or 5 nearest neighbors). But I can not use your library because I work in Visual Studio 2019 and it asks for new and new files/libraries which I can not find here. Maybe you could help me to realize your library I really need it! In which program you realized your library? And maybe you know how else I can realize algorithm of find nearest neighbor. Regards.

**Comment by JCash** [comment]
An example of how to build the library is found in scripts/compile_cl.bat

If you still have issues, please supply more info about the build errors.
