### ISSUE TITLE
Support for Polygons with islands

### ISSUE THREAD

**Issue by esuig** [JCash/voronoi#62]
Hello, 

Great work!

I would like to calculate the radius of the maximum inscribed circle in a polygon with islands and I think using the Voronoi diagram could be the best approach. Something like the situation represented in the following image, were the outher boundary (black) and the islands (red) are the input, while what I want to achieve is the maximum inscribed circle (purple):

![inscr_circle](https://user-images.githubusercontent.com/94478179/150635736-e1d8571c-911d-487a-b936-44ead71502fd.png)

Is it possible to achieve something similar with your library? If yes, is it possble to have an example of use of your library to face the problem I explained?

**Comment by JCash** [comment]
Hi @esuig !

Looking at [this answer](https://math.stackexchange.com/a/1835937), it seems a Voronoi diagram could solve this.

To get the nodes, [iterate over the edges](https://github.com/JCash/voronoi/blob/dev/src/main.c#L577-L579) for the interesting sites, and [get a position](https://github.com/JCash/voronoi/blob/dev/src/jc_voronoi.h#L115) that is shared amongst the interesting sites. That position should represent the center of a circle, and the size is the distance to one of those sites.

Ofc, finding the set of sites to investigate, might be the tricky part.

Also, the "outer boundary" is currently the bounding box of the sites, so you'd have to take that into account as well.
E.g. if you don't find more than 2 site candidates.

**Comment by esuig** [comment]
Thank you for your detailked answer and sorry for my delay wriing back to you.

I've started trying the approach you suggested. I'd like to ask you a question: what do you think would be the best point spacing on the sides of the polygons (both on outer boundary and holes). I mean, if I use just the extremes of each side of the polygon I will not get what I need.

If you need any other detail I can provide you.

Many thanks!
