### ISSUE TITLE
Building a project with code from the voronoi fails in Visual Studio

### ISSUE THREAD

**Issue by etonishev** [JCash/voronoi#78]
Steps to reproduce:
1. Clone the code
2. Create a new console project in the Visual Studio
3. Add a new cpp file and put the following code there:

```
#include <iostream>
#include "jc_voronoi.h"

int main()
{
	return 0;
}
```

4. Go to Solution Explorer -> Project Properties -> C/C++ -> General
5. Add a path to the voronoi\src folder (of the cloned code) in Additional Include Directories property.
6. Apply
7. Try to build Solution by using hotkey Ctrl + B

As the result you will get the following error:

> error C2526: 'jcv_delauney_begin': C linkage function cannot return C++ class 'jcv_delauney_iter_'
> message : see declaration of 'jcv_delauney_iter_'

My environment:
Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.4.4

**Comment by etonishev** [comment]
I try doing the same at home in Visual Studio Community 2022 (64-bit) - Version 17.4.3 and the project was built successfully.

**Comment by JCash** [comment]
Thanks!
I'll try to fix this warning today. It was an oversight on my part. It should be easy to fix by passing in a pointer to the iterator when creating it.

**Comment by etonishev** [comment]
@JCash could you explain why it happens, please? I can't find a good article about this problem in VS.

**Comment by JCash** [comment]
Compile issue is now fixed in https://github.com/JCash/voronoi/releases/tag/v0.9.0
